spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://193.112.155.203:3306/dhomework?characterEncoding=utf-8
    username: root
    password: 1234567

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081
#logging:
#  level:
#    root: info
#    com.rookie: debug
#  file: log/rookie-zheng.log
