spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dhomework?characterEncoding=utf-8
    username: root
    password: 12345678

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
#logging:
#  level:
#    root: info
#    com.rookie: debug
#  file: log/rookie-zheng.log
